name: CI

on:
  push:
  release:
    types:
      - created

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.6', '3.7', '3.8', '3.9', '3.10' ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev.requirements.txt
      - name: Test with pytest
        run: |
          py.test --cov-report xml --cov-report term --cov=opyoid ./tests ./tests_e2e
      - name: Codecov
        if: matrix.python-version == '3.10'
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # python 3.6 has too many false positives
        python-version: [ '3.7', '3.8', '3.9', '3.10' ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev.requirements.txt
      - name: Lint with pylint
        run: |
          pylint opyoid
          pylint tests tests_e2e --disable=too-many-public-methods,no-self-use,too-many-instance-attributes

  deploy:
    needs: [ test, lint ]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'release' }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev.requirements.txt
      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          sed -i "s|version=\"DEV\"|version=\"${GITHUB_REF##*/}\"|g" setup.py
          python setup.py sdist bdist_wheel
          twine upload dist/*
